### ISSUE TITLE
Incorrect WindowsFormSettings?

### ISSUE THREAD

**Issue by krptodr** [DevExpress-Examples/Reporting_how-to-create-a-custom-control-and-register-it-in-the-eud-toolboxwith-a-custom-t461136#1]
Is it correct that this product should be targeting DevExpress v16.* instead of Version 18.*?

It seems that with v16.2 the WindowsFormsSettings.AllowDefaultSvgImages property does not exist. Documentation shows it exists in v18.1 though. 

https://www.devexpress.com/Support/Center/Question/Details/T638346/question-about-18-1-svg-icons

**Comment by vasyaste** [comment]
Yes, this project is compatible with version 16.2. In any case, it is not completely clear to me where you find the information that this property exists in version 18.1 only. I checked the [AllowDefaultSvgImages](https://docs.devexpress.com/WindowsForms/DevExpress.XtraEditors.WindowsFormsSettings.AllowDefaultSvgImages?v=17.2) documentation and this property is described even for version 17.2 there. Our online documentation does not display earlier versions, but this property also exists in earlier versions including version 16.2.
 
Would you please elaborate on what difficulties you faced while running this project by using version 16.2?
